n = input('Digite algo: ')
print('É composto por número e letras? ',n.isalnum())
print('É composto somente por letras maiúsculas? ',n.isupper())
print('É composto somente por letras? ',n.isalpha())
print('É composto somente por números? ',n.isnumeric())
print('É um número decimal? ',n.isdecimal())
print('É composto somente por dígitos? ',n.isdigit())
print('É composto somente por letras minúsculas? ',n.islower())
print('É imprimível? ',n.isprintable())
print('É somente um espaço vazio? ',n.isspace())
print('É um título? ',n.istitle())