f = input('Digite uma frase: ')
f = f.strip()
f1 = f.lower()
n = f1.count('a')
print(f'A letra A aparece {n} vez(es) na frase.')
p1 = f1.find('a')
print(f'A letra A aparece pela primeira vez na posição {p1}.')
p2 = f1.rfind('a')
print(f'A letra A, aparece pela última vez nessa frase na posição {p2}.')
